### DISCUSSION TITLE
Builder for cross-compile on Apple Silicon

### DISCUSSION THREAD

**Discussion by ARui-tw** [abiosoft/colima#1054] [Q&A]
Hi all,

I've been trying to build a Docker image on my M1 Mac with the linux/amd64 architecture, but I haven't had any luck. I tried using Docker Desktop to build it, and it worked as expected. I also installed tonistiigi/binfmt as described [here](https://docs.docker.com/build/building/multi-platform/#qemu-without-docker-desktop), but it still doesn't work. Is there anything I'm missing? Thanks in advance!

- colima.yaml
  ```
  cpu: 8
  disk: 60
  memory: 16
  arch: aarch64
  runtime: docker

  hostname: colima-vz
  
  kubernetes:
    enabled: false
    version: v1.30.0+k3s1
    k3sArgs:
      - --disable=traefik
  autoActivate: true
  network:
    address: false
    dns: []
    dnsHosts: {}
  
  # ===================================================================== #
  # ADVANCED CONFIGURATION
  # ===================================================================== #
  
  forwardAgent: false

  docker: {}
  
  vmType: vz
  rosetta: true
  mountType: virtiofs
  
  mountInotify: true
  cpuType: ""
  provision: []
  sshConfig: true
  mounts: []
  env: {}
  ```
- buildx
  ```
  ❯ docker buildx ls
  NAME/NODE           DRIVER/ENDPOINT     STATUS    BUILDKIT   PLATFORMS
  colima-vz*          docker
   \_ colima-vz        \_ colima-vz       running   v0.13.2    linux/arm64, linux/amd64, linux/amd64/v2, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
  default             docker
   \_ default          \_ default         running   v0.13.2    linux/arm64, linux/amd64, linux/amd64/v2, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
  desktop-linux       docker
   \_ desktop-linux    \_ desktop-linux   running   v0.13.2    linux/arm64, linux/amd64, linux/amd64/v2, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
  ```
- colima
  ```
  ❯ colima version
  colima version 0.6.9
  git commit: c3a31ed05f5fab8b2cdbae835198e8fb1717fd0f
  ❯ colima status vz
  INFO[0000] colima [profile=vz] is running using macOS Virtualization.Framework
  INFO[0000] arch: aarch64
  INFO[0000] runtime: docker
  INFO[0000] mountType: virtiofs
  INFO[0000] socket: unix:///Users/arui/.colima/vz/docker.sock
  ```
