### DISCUSSION TITLE
plex via colima (broadcast discovery UDP)

### DISCUSSION THREAD

**Discussion by fuesec** [abiosoft/colima#1296] [Q&A]
I want to run plex via docker compose through colima on macOS Sequoia 15.4. You can see my setup below. If I choose bridged mode I can reach plex web UI fine from macbook running colima via http://localhost:32400/web and any other machine on the local network via http://{fqdn-of-macbook}:32400/web. However my TV running plex cannot find media library although GDM (plex custom protocol for broadcast discovery via UDP) is turned on. If I change network mode to host in docker compose file I can only reach plex via http://{colima ip address}:32400/ and not on any other device on local network nor can the plex on my tv find the library. If I am in bridged mode and enter  http://{local-ip-address-of-macbook}:32400 under "Custom server access URLs" plex on my tv can find my media library. Do you have any advice of how I can make this work without entering the ip manually in plex server settings? What network mode would I have to choose and what kind of colima settings to get my tv to discover my media library in the most straightforward way?
```
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
   ports:
      - "32400:32400" # Plex
      - "8324:8324"
      - "32469:32469"
      - "1900:1900/udp"
      - "32400:32400/udp"
      - "32410:32410/udp" # Discovery
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - ${CONFIG_BASE_PATH}/plex:/config
      - ${MEDIA_SERVER_BASE_PATH}/media/movies:/mediaserver/media/movies
      - ${MEDIA_SERVER_BASE_PATH}/media/tv:/mediaserver/media/tv
```
