### DISCUSSION TITLE
Mount `/etc/localtime` etc into container

### DISCUSSION THREAD

**Discussion by gabyx** [abiosoft/colima#795] [Q&A]
How can I make `/etc/localtime` in macOS mount into a container?

I tried in `~/.colima//default/colima.yaml`:

```yaml
mounts:
    - location: /etc
      writable: false
```

But that does not work when doing `colima restart`:

`errors inspecting instance: [field `mounts[1].location` must not be a system path such as /etc or /usr]`

Any way of doing this?
