### DISCUSSION TITLE
"Too many open files" when running PostgreSQL

### DISCUSSION THREAD

**Discussion by mvmn** [abiosoft/colima#836] [Q&A]
I'm getting a "too many open files" error when running PostgreSQL with volume mounted to a subfolder in my home dir. Not sure how to increase ulimit.

With Docker Desktop this issue didn't occur.

Lima/Colima documentation seems to have nothing on it.

I tried this in ~/.lima/_config/override.yaml

```
mountType: 9p
mounts:
  - location: "/Users/mvmn/pgsql"
    writable: true
    9p:
      securityModel: mapped-xattr
      cache: mmap
  - location: "~"
    writable: true
    9p:
      securityModel: mapped-xattr
      cache: mmap
  - location: /tmp/colima
    writable: true
    9p:
      securityModel: mapped-xattr
      cache: mmap

provision:
- mode: system
  script: |
    #!/bin/bash
    sysctl -w fs.file-max=500000
```

I needed the mounts to fix no write permission issue for PostgreSQL - and adding this to override.yaml + running colima start with `--mount-type 9p` parameter fixed the issue.

But for ulimit it doesn't seem to do anything despite the added provision script.

P.S. The issue disappears if VM type is changed to VZ (apparently Qemu is the default), and none of the above mentioned configs from override.yaml are needed - but VZ has it's own caveats (can't do ARM on Intel and vice-versa, according to the docs), so it would be nice to figure out a solution that would allow to also use Qemu if needed.

**Comment by abiosoft** [comment]
Can you share the instructions you used to run the postgres container?
Maybe a `docker-compose.yaml` file or a `docker run` snippet?

**Reply by mvmn** [reply]
Sure

Here's a docker-compose.yaml snippet:

```
---
version: '3.9'
services:
  database:
    image: postgres
    container_name: my_db
    restart: 'no'
    volumes:
      - ./my_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1

```

Which I run by doing `docker compose up --build`
