### DISCUSSION TITLE
HAProxy Ports 80 and 443 Permission Denied

### DISCUSSION THREAD

**Discussion by bryanheinz** [abiosoft/colima#852] [Q&A]
I'm attempting to run a HAProxy container, binding to ports 80 and 443. However, I'm getting a Permission Denied error when it tries to bind to the ports:
> haproxy |[ALERT]    (1) : Binding [/usr/local/etc/haproxy/haproxy.cfg:20] for frontend http-in: cannot bind socket (Permission denied) for [0.0.0.0:80]

My host is macOS 13. New Colima install, fairly vanilla config. I haven't touched the network config. Colima appears to have pulled Ubuntu 23.10 by default.

`colima status`:

> INFO[0000] colima is running using macOS Virtualization.Framework
> INFO[0000] arch: aarch64
> INFO[0000] runtime: containerd
> INFO[0000] mountType: virtiofs

Recreation:

- Install Colima on macOS 13
- Config to use the macOS virtualization framework and filesystem
- Run a HAProxy container that binds to 80 and/or 443

I've been searching all over and I can't seem to come up with a solution. I don't think that this is an uncommon use case and the fact that i can't find anyone else with this problem means that I'm probably missing something simple. Maybe it's just the layers of abstraction that are messing me up. Any help is greatly appreciated.

**Comment by abiosoft** [comment]
@bryanheinz can you share your `docker run` command?

**Comment by bryanheinz** [comment]
Of course, albeit I'm using Compose.

```yaml
version: "3"

networks:
    frontend:
        external: true

volumes:
    haproxy_certs:
        external: true

services:
    haproxy:
        image: haproxy:2.8-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
            - haproxy_certs:/haproxy
        container_name: haproxy
        networks:
            frontend:
                aliases:
                    - haproxy
```
