### ISSUE TITLE
Cannot connect to localhost:<exposed_port> after fresh install

### ISSUE THREAD

**Issue by zhibirc** [abiosoft/colima#1064]
### Description

Install Colima in according to repo's README.

Use docker compose, all required containers are run successfully.

Using `colima start --network-address` doesn't help.

Could you please provide me (it may be useful to describe it comprehensively in documentation as well) with the guidance how to enable access from host machine as mentioned? Thanks in advance!

### Version

```
colima version 0.6.9
git commit: c3a31ed05f5fab8b2cdbae835198e8fb1717fd0f

runtime: docker
arch: aarch64
client: v27.0.3
server: v26.1.1
limactl version 0.22.0
qemu-img version 9.0.1
Copyright (c) 2003-2024 Fabrice Bellard and the QEMU Project developers
```

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

```
INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] address: 192.168.106.2
INFO[0000] socket: unix:///Users/username/.colima/default/docker.sock
```

### Reproduction Steps

`docker compose up`

### Expected behaviour

Access my container by `http://localhost:<port>`

**Comment by mikko-ahonen** [comment]
I am having the same issue

**Comment by abiosoft** [comment]
That is strange. Can you share your docker compose file?

**Comment by KholkinDmitrii** [comment]
I had a fully working compose with a .net + postgresql, but after updating to 0.6.10 my compose stopped working, my .net application cannot connect to postgresql. But from my mac i can. Compose file very simple:
```
services:
  app:
    container_name: app
    ports:
      - "3001:3000"
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15.7
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
```
