### ISSUE TITLE
kubernetes has network issues when docker doesn't

### ISSUE THREAD

**Issue by cscetbon** [abiosoft/colima#1068]
### Description

I get network issues in kubernetes pod ran by colima but not in docker containers

### Version

colima version 0.6.9
git commit: c3a31ed05f5fab8b2cdbae835198e8fb1717fd0f

runtime: docker
arch: aarch64
client: v27.0.3
server: v24.0.9
limactl version 0.22.0
qemu-img version 9.0.1
Copyright (c) 2003-2024 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [X] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [ ] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/cscetbon/.colima/default/docker.sock
INFO[0000] kubernetes: enabled

### Reproduction Steps

1. try to install curl using apk in an alpine docker container
```
$ docker run --rm -ti bash sh -c "apk add --no-cache curl"
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz
(1/10) Installing ca-certificates (20240705-r0)
(2/10) Installing brotli-libs (1.1.0-r2)
(3/10) Installing c-ares (1.28.1-r0)
(4/10) Installing libunistring (1.2-r0)
(5/10) Installing libidn2 (2.3.7-r0)
(6/10) Installing nghttp2-libs (1.62.1-r0)
(7/10) Installing libpsl (0.21.5-r1)
(8/10) Installing zstd-libs (1.5.6-r0)
(9/10) Installing libcurl (8.8.0-r0)
(10/10) Installing curl (8.8.0-r0)
Executing busybox-1.36.1-r29.trigger
Executing ca-certificates-20240705-r0.trigger
OK: 15 MiB in 27 packages
```

2. try to install curl using apk in an alpine k8s container
```
$ kubectl run apk -ti --image=bash -- sh -c "apk add --no-cache curl"
If you don't see a command prompt, try pressing enter.
E0716 20:44:19.676684    9392 websocket.go:296] Unknown stream id 1, discarding message
                                                                                       WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: could not connect to server (check repositories file)
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/aarch64/APKINDEX.tar.gz
WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: could not connect to server (check repositories file)
ERROR: unable to select packages:
  curl (no such package):
    required by: world[curl]
Session ended, resume using 'kubectl attach apk -c apk -i -t' command when the pod is running
```

### Expected behaviour

It should work in a kubernetes container as well and not fail because of some network issues

### Additional context

colima's configuration
```
cpu: 2
disk: 60
memory: 5
arch: aarch64
runtime: docker
hostname: colima

kubernetes:
  enabled: false
  
  # Kubernetes version to use.
  # This needs to exactly match a k3s version https://github.com/k3s-io/k3s/releases
  # Default: latest stable release
  version: v1.30.2+k3s2
  
  # Additional args to pass to k3s https://docs.k3s.io/cli/server
  # Default: traefik is disabled
  k3sArgs:
    - --disable=traefik

autoActivate: true

network:
  address: false
  dns: []
  dnsHosts: {}

forwardAgent: false
docker: {}
vmType: qemu
rosetta: false
mountType: sshfs
mountInotify: true
cpuType: ""
provision: []
sshConfig: true
mounts: []
env: {}
```
