### ISSUE TITLE
colima is overwritting ~/.lima/colima/lima.yam during startup

### ISSUE THREAD

**Issue by phaus** [abiosoft/colima#118]
I did update the `~/.lima/colima/lima.yam` to have a write-able access to my userfolder:

```yaml
…
mounts:
    - location: /Users/myuser/
      writable: true
…
```

However, after restarting colima, the config is always reset to `writable: false`.
I also wounder why it is false in the first place, since I created the colima VM with

```bash
colima start --mount $HOME:/Users/myuser:w
```

This issues is blocking me, from migrating from docker for desktop to colima, since I need to have foders within my home user path writable (e.g. for postgres containers).
