### ISSUE TITLE
Unable to bind port 53/udp

### ISSUE THREAD

**Issue by devilmark84** [abiosoft/colima#1198]
### Description

I'm trying to bind port 53/udp of docker CoreDNS image.
This is the `compose.yaml`:

```yaml
services:
  coredns:
    container_name: coredns
    image: coredns/coredns:1.11.4
    ports:
      - "53:53/udp"
    restart: always
    volumes:
      - "./coredns/config:/etc/coredns"
```

While running `docker compose up -d`:

```bash
[+] Running 0/1
 ⠙ Container coredns  Starting                                                                                                                                                0.1s 
Error response from daemon: driver failed programming external connectivity on endpoint coredns (68530047626a699e365f81f5fd232468187d463b61d9617fd7a43a4f400365a9): Error starting userland proxy: listen udp4 0.0.0.0:53: bind: address already in use
```

### Version

colima version 0.6.9
git commit: c3a31ed05f5fab8b2cdbae835198e8fb1717fd0f

runtime: docker
arch: aarch64
client: v26.1.3
server: v24.0.7
limactl version 0.22.0
qemu-img version 9.0.0
Copyright (c) 2003-2024 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [ ] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using macOS Virtualization.Framework 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: virtiofs                          
INFO[0000] address: 192.168.107.2                       
INFO[0000] socket: unix:///Users/marco/.colima/default/docker.sock 

### Reproduction Steps

1.
2.
3.

### Expected behaviour

Bind port 53/udp on the host.

**Comment by devilmark84** [comment]
I understand. On my host the port 53 is free. Is there a way to walk around the port binding on the Colima VM?
I mean, maybe I can bind a different port in the Colima VM, but forward the traffic to my host’s port 53.

**Comment by abiosoft** [comment]
You can start with `--network-address` flag and bind to the IP address instead.

**Comment by devilmark84** [comment]
Can you please write me an example, based on my compose.yaml?

**Comment by abiosoft** [comment]
1. Start Colima with network address enabled

```
colima start --network-address
```

2. Check the IP address assigned from the output of `colima status`. e.g. 192.168.106.2

3. Specify the IP address as part of the port forwarding rule.

```yaml
services:
  coredns:
    container_name: coredns
    image: coredns/coredns:1.11.4
    ports:
      - "192.168.106.2:53:53/udp"
    restart: always
    volumes:
      - "./coredns/config:/etc/coredns"
```
