### ISSUE TITLE
colima ignores template file dns

### ISSUE THREAD

**Issue by gereog** [abiosoft/colima#1218]
### Description

I was getting these errors when trying to start a docker container:

```
failed to solve: redis:7: failed to resolve source metadata for docker.io/library/redis:7: failed to do request: Head "https://registry-1.docker.io/v2/library/redis/manifests/7": dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: no such host
```

So I went into `colima template`, changed `network.dns` to `8.8.8.8`, `8.8.4.4`, then ran `colima restart`

```yaml
# Network configurations for the virtual machine.
network:
  # Custom DNS resolvers for the virtual machine.
  #
  # EXAMPLE
  # dns: [8.8.8.8, 1.1.1.1]
  #
  # Default: []
  dns:
    - 8.8.8.8
    - 8.8.4.4
  

```

I've run `colima restart`, `colima stop`, `colima start`, etc.

Nothing worked, I got exactly the same error message every time

```

### Version

colima version 0.8.0
git commit: 9c08cff339f087c0600d9d56af7b5fbcfe02e287

runtime: docker
arch: aarch64
client: v27.3.1
server: v27.3.1
limactl version 1.0.1

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [ ] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

_No response_

### Reproduction Steps

1.
2.
3.


### Expected behaviour

_No response_

### Additional context

_No response_
