### ISSUE TITLE
Expose Lima setting hostResolver.ipv6

### ISSUE THREAD

**Issue by stek29** [abiosoft/colima#1275]
### Description

currently hostResolver.ipv6 is never set:
https://github.com/abiosoft/colima/blob/e79883bde6581b8ab0db8d0c63103cf4b1e89f8a/environment/vm/lima/yaml.go#L72-L81

however, it's possible to get a somewhat working IPv6 network in container with:
```
network:
  address: true

docker:
  fixed-cidr-v6: SOME-RANDOM-ULA-CIDR::/48
  ipv6: true
```

but the DNS won't resolve AAAA records since `hostResolver.ipv6` property is not set in the lima config.

would be great to allow setting it from the network settings, or to even set it to true automatically if `network.address` is set to true in Colima spec.
