### ISSUE TITLE
SSH port forwarding options

### ISSUE THREAD

**Issue by asharpe** [abiosoft/colima#1282]
### Description

Lima supports SSH forwarding (https://github.com/lima-vm/lima/pull/836) in a way that allows making the `gpg-agent` socket available inside the VM.

It'd be great to expose the ability to adjust the underlying SSH config to allow port forwarding on the main SSH master.

**Comment by asharpe** [comment]
Turns out this is available via the global override (in `~/.colima/_lima/_config/override.yaml`) with something like

```
portForwards:
    - reverse: true
      hostSocket: "/Users/{{.User}}/.gnupg/S.gpg-agent"
      guestSocket: "/run/user/{{.UID}}/gnupg/S.gpg-agent"
      hostPortRange: [0, 0]
      guestPortRange: [0, 0]
```

To make this "just work" inside the VM, I have these provisioning steps (in `~/.colima/default/colima.yaml`, could probably just go in the override file too)

```
provision:
  - mode: user
    script: |
      systemctl --user mask gpg-agent.socket
  - mode: user
    script: |
      echo -e "no-autostart\nquiet\n" > ~/.gnupg/gpg.conf
  - mode: user
    script: |
      cp /Users/$USER/.gnupg/pubring.kbx ~/.gnupg/
```

Thanks for the awesome software! 😄
