### ISSUE TITLE
K3s Ingress controller not deployed

### ISSUE THREAD

**Issue by myannou** [abiosoft/colima#133]
when using colima with kubernets:
`colima start --with-kubernetes`

a k3s cluster is correctly deployed but without an Ingress controller.
Normally k3s comes with a [traefik-ingress-controller](https://rancher.com/docs/k3s/latest/en/networking/#traefik-ingress-controller).

I found this has been disabled in [k3s.go](https://github.com/abiosoft/colima/blob/57469b9e8c02404498e134f1afb0f824424fa768/environment/container/kubernetes/k3s.go#L98)

I wonder why ?

I can deploy myself an Ingress controller but then how to do a port-forwarding of the ingress port ?

**Comment by abiosoft** [comment]
The wide variety of versions and setup for Kubernetes is the main reason for opting for the minimal Kubernetes setup.

For more complex uses cases, there are more feature packed docker-based solutions that will work with colima e.g. minikube (with docker driver), kind and k3d.



> I can deploy myself an Ingress controller but then how to do a port-forwarding of the ingress port ?
 
This should not be a problem as port forwarding is automatic.

**Comment by myannou** [comment]
I don't consider ingress usage in k8s as a complex use case but more a basic & standard usecase of kubernetes.
but, I understand your point
I didn't know how port forwarding worked, so thanks for the clarification
So I will now see how to deploy k3d in colima
thanks

**Comment by myannou** [comment]
As it could help for others, here is what I did to automatically deploy an ingress:
in the  `~/.lima/_config/override.yaml` file I added:
```
provision:
- mode: system
  script: |
    #!/bin/bash
    mkdir -p /var/lib/rancher/k3s/server/manifests
    cat > /var/lib/rancher/k3s/server/manifests/helm-ingress-nginx.yaml << EOF
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: ingress-controller-nginx
      namespace: kube-system
    spec:
      repo: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.0.17
      targetNamespace: kube-system
      valuesContent: |-
        controller:
          service:
            ports:
              http: 8080
              https: 8043
          watchIngressWithoutClass: true
          ingressClassResource:
            default: true
    EOF
```

and that's all!

Each time you will create a colima vm: `colima start --with-kubernetes --runtime containerd`
this will also deploy a nginx ingress in K3S
It relies on 2 features of k3s:
* ‘Auto-Deploying Manifests’ A practical feature of k3s: Any file found in /var/lib/rancher/k3s/server/manifests will automatically be deployed to Kubernetes in a manner similar to kubectl apply
* Helm charts Operator: K3s includes a Helm Controller that manages Helm charts using a HelmChart Custom Resource Definition (CRD)

And so the ingress port 8080/8043 will be also "port forwarde" on your host

Hope it can help others
