### ISSUE TITLE
Mounting an external hard drive

### ISSUE THREAD

**Issue by gablilli** [abiosoft/colima#1334]
Hi guys.
i'm here asking if there's a way to mount an external hard drive in colima (I'm trying to run there casaos).
I tried editing the .yaml like this:
```
name:default
mounts:
 - location: /Volumes/Seagate
   mountPoint: /seagate
   writable: true
```
but with ls, the directory is not there:
```
ls /seagate
ls: cannot access '/seagate': No such file or directory
```

Any way to do this?
