### ISSUE TITLE
Colima v 0.2.0 - error while starting colima

### ISSUE THREAD

**Issue by vraravam** [abiosoft/colima#20]
I have removed the `~/.docker` folder completely. I have also installed `v0.2.0` of colima.

When I run `colima start`, this is the error that I get:
```
error provisioning docker: error at 'provisioning': error copying deamon.json: exit status 1
```

**Comment by abiosoft** [comment]
Thanks for trying this out so quickly. This is strange as I have not been able to reproduce this.

Do you have an existing version of colima running?
What lima version do you have?
Is the vm created on lima? check with `limactl ls`

**Comment by vraravam** [comment]
Contents of my `cat ~/.lima/colima/lima.yaml`
```
arch: "default"
images:
  - location: "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-arm64.img"
    arch: "aarch64"
cpus: 3
memory: "6GiB"
disk: "75GiB"
mounts:
  - location: "~"
    # CAUTION: writable SHOULD be false for the home directory.
    # Setting writable to true is possible, but untested and dangerous.
    writable: false
  - location: "/tmp/colima"
    writable: true
ssh:
  localPort: 41122
  loadDotSSHPubKeys: false
containerd:
  system: false
  user: false
firmware:
  legacyBIOS: false
```
