### ISSUE TITLE
Help forwarding ports from docker-compose

### ISSUE THREAD

**Issue by jvzaniolo** [abiosoft/colima#255]
Hey,

I have this docker-compose

```yaml
version: "2"
services:
  frontend:
    ports:
     - "80:80"
     - "443:443"
    extra_hosts:
    - "dev.frontend.com:${HOSTIP}"
```

If I do, `colima start; docker-compose up; colima ssh; ping dev.frontend.com` it works
But if I do `ping dev.frontend.com` outside colima, it doesn't work (timeout err)

I also have this in my `/etc/hosts` file:

`127.0.0.1 dev.frontend.com`

Is this because of forwarding ports not working?

**Comment by jvzaniolo** [comment]
Not sure if I was clear enough but what I want to do is connect to `dev.frontend.com` outside colima's VM

**Comment by jvzaniolo** [comment]
Running `docker ps` outside Colima's VM
```
CONTAINER ID   IMAGE       COMMAND              CREATED          STATUS         PORTS                                                                      NAMES
9787418c3675   httpd:2.4   "httpd-foreground"   22 minutes ago   Up 3 seconds   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   docker-frontend-1
```

**Comment by abiosoft** [comment]
what version are you running? `colima version`
is anything else running on ports 80 and 443?

**Comment by jvzaniolo** [comment]
Hey, it seems to be working now. I deleted the ~/.docker folder and it started working again.

But colima is at 0.3.4 and nothing else is running on ports 80 or 443

**Comment by rlewkowicz** [comment]
I don't want to open a whole nother bug I already know the answer to. I'll tac on here to "general network issues" unless that's frowned on. 

https://github.com/lima-vm/lima/issues/366

I can say that I forwarded udp, but it doesn't seem to work, and I think this is why.

**Comment by cam-narzt** [comment]
I have pretty much the same problem afaict.

`docker-compose.yml`:
```yaml
---
version: '3.4'
services:
  app:
    build: .
    environment:
      PYTHONPATH: /code/src
    ports:
    - 5000:5000
...
```

```
$ colima --version
colima version 0.6.8
$ docker compose version
Docker Compose version 2.25.0
$ lima --version
limactl version 0.21.0
$ docker version
Client: Docker Engine - Community
 Version:           25.0.5
 API version:       1.44
 Go version:        go1.22.1
 Git commit:        5dc9bcc5b7
 Built:             Tue Mar 19 14:51:10 2024
 OS/Arch:           darwin/amd64
 Context:           colima

Server: Docker Engine - Community
 Engine:
  Version:          25.0.4
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       061aa95
  Built:            Wed Mar  6 16:32:10 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
 $ colima status
INFO[0000] colima is running using macOS Virtualization.Framework 
INFO[0000] arch: x86_64                                 
INFO[0000] runtime: docker                              
INFO[0000] mountType: virtiofs                          
INFO[0000] socket: unix:///Users/camdennarzt/.colima/default/docker.sock
```

`~/.colima/default/colima.yaml`:
```yaml
cpu: 2
disk: 60
memory: 4
arch: host
runtime: docker
hostname: colima
kubernetes:
  enabled: false
  version: v1.25.4+k3s1
  k3sArgs: []
autoActivate: true
network:
  address: false
  dns:
    - 1.1.1.1
  dnsHosts: {}
forwardAgent: false
docker: {}
vmType: vz
rosetta: false
mountType: virtiofs
mountInotify: false
cpuType: ""
provision: []
sshConfig: false
mounts: []
env: {}
```

```
$ lsof -Pi :5000
COMMAND  PID        USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
ssh     1352 camdennarzt   22u  IPv4 0x3e040ef6c39fc2b9      0t0  TCP *:5000 (LISTEN)
$ ps 1352
  PID   TT  STAT      TIME COMMAND
 1352   ??  Ss     0:00.73 ssh: /Users/camdennarzt/.colima/_lima/colima/ssh.sock [mux] 
```

```
$ curl http://127.0.0.1:5000
curl: (52) Empty reply from server
$ docker ps
CONTAINER ID   IMAGE              COMMAND            CREATED              STATUS              PORTS                                       NAMES
89090378e18b   python-flask-app   "python3 app.py"   About a minute ago   Up About a minute   0.0.0.0:5000->5000/tcp, :::5000->5000/tcp   python-flask-app-1
$ docker exec python-flask-app-1 curl http://127.0.0.1:5000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   651  100   651    0     0   108k      0 --:--:-- --:--:-- --:--:--  127k
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Upload new File</title>
    <!-- link rel="stylesheet" href="style.css" -->
    <!-- script src="script.js"></script -->
  </head>
  <body>
    <h1>Upload new File for pt1</h1>
    <form method="post" enctype="multipart/form-data" action="/pt1/process">
      <input type="file" name="file">
      <input type="submit" value="Upload">
    </form>
    <h1>Upload new File for pt2</h1>
    <form method="post" enctype="multipart/form-data" action="/pt2/process">
      <input type="file" name="file">
      <input type="submit" value="Upload">
    </form>
  </body>
</html>
```
