### ISSUE TITLE
Enabling a `shared` or `bridged` network causes `lima kubectl cluster-info` to fail

### ISSUE THREAD

**Issue by spkane** [abiosoft/colima#375]
### Description

`colima` is unable to verify that the Kubernetes has started correctly when a `shared` or `bridged` network is used for the underlying VM.

### Version

Colima Version: 0.4.4
Lima Version: 0.11.2
Qemu Version: 7.0.0

### Operating System

- [X] macOS Intel
- [ ] macOS M1
- [ ] Linux

### Reproduction Steps

This used to work, but started failing at some point.

I have set up networking for `lima` as discussed here:

https://github.com/lima-vm/lima/blob/master/docs/network.md

And then in this file: `.lima/_config/override.yaml` I have this:

```yaml
networks:
  - lima: bridged
```

When I try to start `colima` with the network uncommented then I get:

```console
INFO[0000] starting colima
INFO[0000] runtime: containerd+k3s
INFO[0000] preparing network ...                         context=vm
INFO[0000] starting ...                                  context=vm
INFO[0030] provisioning ...                              context=containerd
INFO[0030] starting ...                                  context=containerd
INFO[0036] provisioning ...                              context=kubernetes
INFO[0037] starting ...                                  context=kubernetes
FATA[0062] error starting kubernetes: error running [lima kubectl cluster-info], output: "The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?", err: "exit status 1"
```

### Expected behaviour

I would expect the VM to come up with no errors and everything in a useable state.

**Comment by abiosoft** [comment]
Why not simply use `--network-address` flag? 
Is there anything extra you have in your Lima override config other than specifying the network?

**Comment by spkane** [comment]
I do not have anything else in the override file. As a matter of fact, I completely removed my `lima` and `colima` installs and started from scratch while I was trying to troubleshoot this.

This had been working fine in the past, so I was surprised that it stopped working and caused `colima` to generate an error during startup. I'll take a look at that flag and see if I can make it work.

https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#the-virtual-machines-ip-is-not-reachable

**Comment by abiosoft** [comment]
If all you need is a reachable IP address, I would recommend you do that with Colima directly. 
Lima overrides are for advanced use-cases and they are not always guaranteed to work, especially when Colima also generates similar config.

>  I'll take a look at that flag and see if I can make it work.

It is easier than you think. Simply start with `colima start --network-address` and view the IP address with `colima list`.

**Comment by spkane** [comment]
I am a bit confused with the solution that you are recommending, only because this ticket is about the fact the `colima` generates an error during startup in this situation.

I am not trying to run `lima kubectl cluster-info` myself.

**Comment by abiosoft** [comment]
Yeah, colima runs the command as part of the startup for kubernetes to ensure that the startup is successful.
Does it work if you comment out the network config in the lima override file?

What I suspect is that k3s bootstraps using the vmnet IP address and thereby unreachable without using the IP.

**Comment by spkane** [comment]
Yes. It works when the network override is commented out. That additional info is helpful. Thanks.

Ok, adding `--network-address` seems to have resolved the error, although I see *INFO[0000] dependencies missing for setting up reachable IP address  context=vm* in the output It still isn't clear to me exactly what is going on, but I'll experiment a bit with it.

`colima start --cpu 8 --memory 8 --disk 100 --runtime containerd --with-kubernetes --network-address`

**Comment by ipv1337** [comment]
This is the closest issue I can find related to what I'm trying to achieve setting up a bridged network mode.  

I have yet to see how to configure colima to start up the VM using my own network dhcp so I can get a real IP off my network.  When I do try to add the network override.yaml for lima, I can start colima fine, but my network override in lima does not setup a bridge the way I'd expect it to.

My override is simple:

```
networks:
   - lima: bridged
```

Is this even possible?  I've googled this many times and have found little information on this topic.  Any help is much appreciated.

**Comment by jandubois** [comment]
This should work, as long as your host network interface is `en0`. Maybe you are using a different one. You can find the most likely candidate with (assuming you have `jq` installed; otherwise you have to pick it out yourself):

```
$ system_profiler SPNetworkDataType -json | jq -r 'first(.SPNetworkDataType[] | select(.ip_address) | .interface)'
en0
```

Then check your `~/.lima/_config/networks.yaml` file for the definition of the `bridged` network:

```
networks:
  bridged:
    mode: bridged
    interface: en0
```

Make sure your host interface name matches the one in the `bridged` definition.

**Comment by ipv1337** [comment]
Hi @jandubois thanks for you quick response.  I am using `en0` actually as you can see here also:
```
└[~]> system_profiler SPNetworkDataType -json | jq -r 'first(.SPNetworkDataType[] | select(.ip_address) | .interface)'
en0
```

Here's what my `~/.lima/_config/networks.yaml` file looks like which is the default:
```
└[~]> cat ~/.lima/_config/networks.yaml
# Path to socket_vmnet executable. Because socket_vmnet is invoked via sudo it should be
# installed where only root can modify/replace it. This means also none of the
# parent directories should be writable by the user.
#
# The varRun directory also must not be writable by the user because it will
# include the socket_vmnet pid file. Those will be terminated via sudo, so replacing
# the pid file would allow killing of arbitrary privileged processes. varRun
# however MUST be writable by the daemon user.
#
# None of the paths segments may be symlinks, why it has to be /private/var
# instead of /var etc.
paths:
# socketVMNet requires Lima >= 0.12 .
# socketVMNet has precedence over vdeVMNet.
  socketVMNet: "/opt/socket_vmnet/bin/socket_vmnet"
# vdeSwitch and vdeVMNet are DEPRECATED.
  vdeSwitch: /opt/vde/bin/vde_switch
  vdeVMNet: /opt/vde/bin/vde_vmnet
  varRun: /private/var/run/lima
  sudoers: /private/etc/sudoers.d/lima

group: everyone

networks:
  shared:
    mode: shared
    gateway: 192.168.105.1
    dhcpEnd: 192.168.105.254
    netmask: 255.255.255.0
  bridged:
    mode: bridged
    interface: en0
    # bridged mode doesn't have a gateway; dhcp is managed by outside network
  host:
    mode: host
    gateway: 192.168.106.1
    dhcpEnd: 192.168.106.254
    netmask: 255.255.255.0
```

This is how I'm trying to start colima:
```
$ colima start --cpu 8 --memory 8 --disk 100 --vm-type qemu --runtime containerd --kubernetes --activate --network-driver slirp --network-address
```

Here's something I observed from `/etc/sudoers.d/colima` that might help?
```
└[/etc/sudoers.d]> cat colima
# starting vmnet daemon
%staff ALL=(root:wheel) NOPASSWD:NOSETENV: /opt/colima/bin/socket_vmnet --vmnet-mode shared --socket-group staff --vmnet-gateway 192.168.106.1 --vmnet-dhcp-end 192.168.106.254 *
# terminating vmnet daemon
%staff ALL=(root:wheel) NOPASSWD:NOSETENV: /usr/bin/pkill -F /opt/colima/run/*.pid
# validating vmnet daemon
%staff ALL=(root:wheel) NOPASSWD:NOSETENV: /usr/bin/pkill -0 -F /opt/colima/run/*.pid
```

That is the network IP my colima instance keeps getting instead of my own home network IP that `en0` gets.
