### ISSUE TITLE
How to change kernel variables so they persist 2.0

### ISSUE THREAD

**Issue by mkrauser** [abiosoft/colima#384]
### Description

This is kind of the same Problem as described in #319.

To run opensearch in a container, the value of vm.max_map_count needs to be increased (see https://opensearch.org/docs/1.1/opensearch/install/important-settings/).

I can do this while colima is running with `colima ssh` and `sysctl -w vm.max_map_count= 262144`, but my attempts to make this change persistent were not successful.

I tried editing /etc/sysctl.conf as well as creating a new file in etc/sysctl.d/, bit this had no effect.

### Version

Colima Version:

```
$ colima version
colima version 0.4.4
git commit: 8bb1101a861a8b6d2ef6e16aca97a835f65c4f8f

runtime: docker
arch: x86_64
client: v20.10.14
server: v20.10.11
```

Lima Version:
```
$ limactl --version
limactl version 0.11.2
```
Qemu Version:
```
$ qemu-img --version
qemu-img version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

### Operating System

- [X] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1. Add a kernel-setting (e.g. vm.max_map_count) via /etc/sysctl.conf or a separate file in /etc/sysctl.d
2. restart colima
3. check, if that the setting has been applied (e.g. cat /proc/sys/vm/max_map_count)

### Expected behaviour

The value from the config-file should have been applied

### Additional context

This can probably be fixed like #319 which would indeed solve my problem, but a more general solution would be preferable.

Anyway, Thank you so much for your work!

**Comment by abiosoft** [comment]
Yeah, I'm working on this. Basically an option for provision scripts that would cater for scenarios like this.

**Comment by mkrauser** [comment]
> Yeah, I'm working on this. Basically an option for provision scripts that would cater for scenarios like this.

Nice, looking forward to this

**Comment by abiosoft** [comment]
Kindly install the development version with `brew install --HEAD colima` as this would not be available in stable until the next release.

* Start with --edit flag.
  ```
  colima start --edit 
  ```

* Specify the provision commands/script under the `provision` section.
  ```diff
  - provision: []
  + provision:
  +   mode: system
  +   script: sysctl -w vm.max_map_count=262144
  ```

**Comment by amanos1022** [comment]
> Kindly install the development version with `brew install --HEAD colima` as this would not be available in stable until the next release.
> 
> * Start with --edit flag.
>   ```
>   colima start --edit 
>   ```
> * Specify the provision commands/script under the `provision` section.
>   ```diff
>   - provision: []
>   + provision:
>   +   mode: system
>   +   script: sysctl -w vm.max_map_count=262144
>   ```

I had to change up your suggestion a bit (`provision` is an array of objects):
```
provision:
  - mode: system
    script: sysctl -w vm.max_map_count=262144
```
This did indeed fix my root issue which was Elasticsearch `max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]` error

Thanks for your hard work on this!

**Comment by davedecoder** [comment]
For the folks who are trying to use `elasticsearch:7.*.*` with docker compose instead. this setup worked for me:

1. Do these steps as @amanos1022 and  @abiosoft suggested: https://github.com/abiosoft/colima/issues/384#issuecomment-1235753254

2. In your docker compose  file:
```
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch
    environment:
      - cluster.initial_master_nodes=nodo1
      - node.name=nodo1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms900m -Xmx900m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    expose:
      - 9200
```
