### ISSUE TITLE
Shared Bind Mount in docker compose fails to mount

### ISSUE THREAD

**Issue by ramarnat** [abiosoft/colima#397]
### Description

in my docker-compose.yml, I have defined a shared bind mount:

```
volumes:
  aws:
    driver: local
    driver_opts:
      type: none
      device: ./local/somedir/
      o: bind
```

Gives an error
```
Error response from daemon: error while mounting volume '/var/lib/docker/volumes/project-dir_somedir/_data': failed to mount local volume: mount ./local/somedir/:/var/lib/docker/volumes/project-dir_somedir/_data, flags: 0x1000: no such file or dir
```

Looks like it isnt interpreting the `.` as the mounted directory inside colima

### Version

Colima Version:
```
colima version 0.4.4
git commit: 8bb1101a861a8b6d2ef6e16aca97a835f65c4f8f

runtime: docker
arch: aarch64
client: v20.10.17
server: v20.10.11
```

Lima Version:
```
limactl version 0.11.2
```
Qemu Version:
```
qemu-img version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developer
```

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1. Create a docker-compose file with a shared bind mount as described above (`./somedir`, as the local mount directory)
2. docker-compose up

### Expected behaviour

It should map  as /<lima mount directory>/local/somedir/:/var/lib/docker/volumes/project-dir_somedir/_data

**Comment by ramarnat** [comment]
Looks like this worked:
```
volumes:
  aws:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/local/somedir/
      o: bind
```

I think I tried this before and it did not, but I realized I had to drop the volume, it does not get dropped even if the container is removed and `docker-compose down` is called.
