### ISSUE TITLE
buildx multi-platform docker builds fail

### ISSUE THREAD

**Issue by dustinrue** [abiosoft/colima#44]
Definitely not sure if this would go here or in lima but I'm unable to do multi-arch builds using buildx. Here is an example error that I get

```
docker buildx build . -t base-php --platform linux/amd64,linux/arm64
...
#12 36.47 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
Dockerfile:9
--------------------
   8 |
   9 | >>> RUN \
  10 | >>>   apt update && \
  11 | >>>   apt dist-upgrade -y && \
  12 | >>>   apt install gnupg -y && \
  13 | >>>   apt clean
  14 |
--------------------
error: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/bash -c apt update &&   apt dist-upgrade -y &&   apt install gnupg -y &&   apt clean" did not complete successfully: exit code: 100
```

I get this same error on both my 2018 i7 Mac mini and my 2020 M1 MBA. 

This is my config

```
vm:
    cpu: 6
    disk: 60
    memory: 6
    mounts:
        - /Users/dustin/wp-local-docker-sites:w
        - /Users/dustin/.wplocaldocker:w
runtime: docker
kubernetes:
    enabled: false
    version: v1.22.2
```
