### ISSUE TITLE
feat: add support for setting kubernetes server port (or automate based on profiles to avoid overlap)

### ISSUE THREAD

**Issue by dmccaffery** [abiosoft/colima#467]
### Description

When starting two instances of colima, both with kubernetes enabled, they use the same server port mapped to the host (6443). Only the first instance is mapped correctly. When the kube config context is activated, it no longer works as the certificates do not align.

Expected:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0t...
    server: https://127.0.0.1:6443
  name: colima
- cluster:
    certificate-authority-data: LS0t...
    server: https://127.0.0.1:6444
  name: colima-backup
```

Actual:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0t...
    server: https://127.0.0.1:6443
  name: colima
- cluster:
    certificate-authority-data: LS0t...
    server: https://127.0.0.1:6443
  name: colima-backup
```

You can switch between the two, obviously, but its nice to be able to run different versions of kubernetes, or different instances to support a backup in demo / presentation settings.

**Comment by abiosoft** [comment]
If you start with network address enabled, it would avoid the clash. 

But yeah, that's a good point you raised. 

```
colima start --network-address
```

**Comment by blast-hardcheese** [comment]
I need a solution that works on all platforms, so currently I'm doing:

```bash
$ colima start
$ colima ssh bash -- -c 'cat /etc/colima/colima.json 2>/dev/null || echo {}' \
    | jq --argjson colima_json '{"k3s_listen_port":"6443"}' \
    '. + $colima_json' \
    | colima ssh sudo tee /etc/colima/colima.json
$ colima kubernetes start
```

I understand this issue is over a year old at this point. Given that, I suspect

```yaml
# Kubernetes configuration for the virtual machine.
kubernetes:
  # Enable kubernetes.
  # Default: false
  enabled: true

  listen_port: 6443
```

would be the most sensible place to add that setting.

@abiosoft I'm happy to PR, if this is acceptable? I'd really like to reduce the complexity of VM init 🙂
