### ISSUE TITLE
Colima hangs a short while after starting

### ISSUE THREAD

**Issue by blame-git** [abiosoft/colima#552]
### Description

Shortly after starting a colima instance it seem to hang, and I’m unable to ssh into the session

```
% colima -v start -t vz -c 8 -m 8 --mount /Volumes/Void:w --mount-type virtiofs --mount /Volumes/Stash:w --mount-type virtiofs --mount /Volumes/Vacuum:w --mount-type virtiofs

% colima list
PROFILE    STATUS     ARCH       CPUS    MEMORY    DISK     RUNTIME    ADDRESS
default    Running    aarch64    8       8GiB      60GiB    docker     

# Roughly 5~10 minutes later
% colima ssh
FATA[0006] exit status 255
```

From `~/.lima/colima/ha.stderr.log` I see:
```

{"level":"error","msg":"write unixgram -\u003e: write: no buffer space available","time":"2022-12-30T11:24:42-08:00"}
{"level":"error","msg":"cannot receive packets from , disconnecting: cannot read size from socket: read unixgram -\u003e: use of closed network connection","time":"2022-12-30T11:24:42-08:00"}{"level":"error","msg":"virtual network error: \"cannot read size from socket: read unixgram -\u003e: use of closed network connection\"","time":"2022-12-30T11:24:42-08:00"}
```

- [ ] 

### Version

Colima Version:
```
colima version HEAD-88390f5
git commit: 88390f54bceb72e248044aa3b452b64c676d99d1
```
Lima Version: `limactl version 0.14.2`
Qemu Version: `qemu-img version 7.2.0`
macOS Version: `13.1 22C65`

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

```
% colima status
FATA[0003] error retrieving current runtime: empty value
```

vm-type: `vz`
mount type: `virtiofs`

### Reproduction Steps

1. Start Colima
2. 3 Docker containers start
3. Wait about 5-10 minutes

**Comment by abiosoft** [comment]
Thanks for reporting this. I have experienced same with the VZ vm type and still troubleshooting.

If you do not need the faster filesystem access, QEMU is more stable.

**Comment by balajiv113** [comment]
@blame-git 
If you could mention about the kind of network activity happening around that time (even your running containers info if possible) it would help debug/fix this issue better.

I have been trying to reproduce this but couldn't find a way

**Comment by abiosoft** [comment]
@balajiv113 I am not sure what fixed it precisely but I'm suspecting its https://github.com/lima-vm/lima/pull/1261.

I am still monitoring it but it seems to have stabilised now and no longer freezing.

**Comment by Sangeppato** [comment]
I'm still experiencing this issue from time to time, but I haven't found a way to systematically reproduce it

**Comment by blame-git** [comment]
I’m still able to reproduce, but it is less frequent now.  What seems to do it for me, is using a container that downloads files from the internet at high speed, and writing them out to volumes (mounted via virtiofs)

**Comment by blame-git** [comment]
Oops, didn’t meant to close

**Comment by balajiv113** [comment]
@blame-git 
> What seems to do it for me, is using a container that downloads files from the internet at high speed, and writing them out to volumes

Is this steps makes colima hang ?? If yes, can you share some command to redo this steps??

**Comment by mcelen35** [comment]
Bumping, I'm have the exact same issue.

**Comment by developerrespig** [comment]
Also having this issue and it drives me nuts :(

**Comment by mcelen35** [comment]
@balajiv113, there's no weird steps actually.

Just start colima, start couple of containers, it hangs after 5 min.

I have mongodb,nats,mysql,redis (from bitnami) containers only, within a custom network.

**Comment by balajiv113** [comment]
> I have mongodb,nats,mysql,redis (from bitnami) containers only, within a custom network.

If you could share the docker-compose for this setup it would be great.

**Comment by mcelen35** [comment]
> > I have mongodb,nats,mysql,redis (from bitnami) containers only, within a custom network.
> 
> If you could share the docker-compose for this setup it would be great.

Here you go

```
version: '3'
services:
  nats:
    image: nats:latest
    container_name: nats
    networks:
      - placeholder
    expose:
      - 4222
    ports:
      - "4222:4222"
  mongodb:
    image: ghcr.io/zcube/bitnami-compat/mongodb:6.0.3-debian-11-r51
    container_name: mongodb
    environment:
      - MONGODB_USERNAME=placeholder
      - MONGODB_PASSWORD=placeholder
      - MONGODB_DATABASE=backend
      - MONGODB_ROOT_PASSWORD=root
    networks:
      - placeholder
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb:/bitnami'

  redis:
    image: ghcr.io/zcube/bitnami-compat/redis:7.0.7-debian-11-r51
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - placeholder
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/bitnami'
  mysql:
    image: ghcr.io/zcube/bitnami-compat/mysql:8.0.31-debian-11-r51
    container_name: mysql
    environment:
      - MYSQL_USER=placeholder
      - MYSQL_PASSWORD=placeholder
      - MYSQL_DATABASE=placeholder
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - placeholder
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - 'mysql:/bitnami'
networks:
  placeholder:
    external: true
volumes:
  mongodb:
    driver: local
    name: placeholder-mongodb
  mysql:
    driver: local
    name: placeholder-mysql
  redis:
    driver: local
    name: placeholder-redis
```
