### ISSUE TITLE
accessing colima kubernetes node by ip

### ISSUE THREAD

**Issue by tzookb** [abiosoft/colima#584]
### Description

I'm playing around with K8S. I have svc.yaml file:
```
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: hello-world
```

that suppose to forward one of my pods 8080 port to my colima port 30001

but I can find the colima IP.

Asked on StackOverflow as well: https://stackoverflow.com/questions/75123014/how-to-access-pods-from-host

### Version

Colima Version:0.5.1
Lima Version:0.14.2
Qemu Version:7.2.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [X] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU
INFO[0000] arch: x86_64
INFO[0000] runtime: docker
INFO[0000] mountType: 9p
INFO[0000] socket: unix:///Users/tzookb/.colima/default/docker.sock
INFO[0000] kubernetes: enabled

### Reproduction Steps

1. `kubectl describe node colima`
2. find `InternalIP` for me its: `192.168.5.15`
3. run `ping 192.168.5.15` no response

### Expected behaviour

I should be able to reach to colima master node.
