### ISSUE TITLE
access colima node through kafka port

### ISSUE THREAD

**Issue by tzookb** [abiosoft/colima#601]
### Description

running Colima with reachable ip: colima start --network-address

then colima list

PROFILE      STATUS     ARCH      CPUS    MEMORY    DISK      RUNTIME    ADDRESS
default      Running    x86_64    4       8GiB      100GiB    docker     192.168.106.2
and after the above, I'm running my docker-compose:

```
version: "3"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
``` 

So I'm basically forwarding port "9092" on the kafka container to the host port "9092".

I tried to reach kafka through:

- "192.168.106.2:9092"
- "192.168.106.2"
- "127.0.0.1:9092"
- "localhost:9092"
- "0.0.0.0:9092"

but I getting an error. I know kafka container is working as I can access it, if Im trying to use it through a container inside the docker network.

how can I access it from my host machine?

### Version

Colima Version:0.5.1
Lima Version:0.14.2
Qemu Version:7.2.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [X] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU
INFO[0000] arch: x86_64
INFO[0000] runtime: docker
INFO[0000] mountType: 9p
INFO[0000] address: 192.168.106.2
INFO[0000] socket: unix:///Users/tzookb/.colima/default/docker.sock

### Reproduction Steps

1. shared in the desctiption

### Expected behaviour

able to connect to the kafka port

### Additional context

https://stackoverflow.com/questions/75278243/colima-access-to-kafka-port-with-docker
