### ISSUE TITLE
Unable to recognize file changes inside Docker container or VM

### ISSUE THREAD

**Issue by docmg** [abiosoft/colima#649]
### Description

I am running my docker containers in Colima and filewatchers do not recognise changes if mountType is set to `sshfs`  or `virtiofs`. Even if i enter VM using `colima ssh` and execute`tail -f somefilex.txt` -> tail do not  recognise the changes made by the host system. But if i print file content using `cat` out, new content is showing up in console.

After changing mounType to 9p, `tail -f` starts to recognise the changes, but webpack is still not working.
I made some Tests using chokidar and got the same results as with `tail -f`.

### Version

Hardware & OS
Processor: 2,4 GHz 8-Core Intel Core i9
Memory: 32 GB
MacOS: 13.1 Ventura (22C65) 

Colima Version: 0.5.2
Lima Version: 0.14.2
Qemu Version: 7.2.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [X] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU
INFO[0000] arch: x86_64
INFO[0000] runtime: docker
INFO[0000] mountType: 9p
INFO[0000] socket: unix:///Users/docmg/.colima/default/docker.sock

### Reproduction Steps

1. Start VM
`colima start --cpu 4 --memory 8 --disk 128 --mount-type 9p --vm-type qemu`

2. Create and open new directory colima-test
`mkdir colima-test && cd colima-test`

3. Create new react app
`npx create-react-app frontend`

4. Create new Dockerfile in frontend directory and edit it.
`touch frontend/Dockerfile`

Dockerfile:
```Dockerfile
FROM node:18
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
EXPOSE 3000
CMD ["npm", "start"]
```

5. Create new docker-compose.yml in colima-test directory and edit it.
`touch docker-compose.yml`

docker-compose.yml:
```yaml
version: "3.4"

services:
  frontend:
    container_name: frontend-react
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - default

networks:
  default:
    driver: bridge
```

6. Start container
`docker-compose up

7. Open localhost:3000 in your browser and try to edit files in src directory.

### Expected behaviour

I expect webpack to recognize file changes and print something in the console or update data in my browser tab, but nothing happens. Everything worked well while using docker Desktop. 

### Additional context

I found one more person at stackoverflow with probably the same Problem, but unfortunately there is only my answer to this Question.
https://stackoverflow.com/questions/75549535/colima-is-unable-to-recognize-file-changes-inside-docker-container
