### ISSUE TITLE
DNS not resolving AWS domains

### ISSUE THREAD

**Issue by gpsa** [abiosoft/colima#674]
### Description

**When I (rely on colima's internal DNS):**

```shell
nslookup test.s3-website-us-east-1.amazonaws.com

Server:		192.168.107.1
Address:	192.168.107.1:53

Non-authoritative answer:

** server can't find test.s3-website-us-east-1.amazonaws.com: NXDOMAIN
```

**But if I use Google's 8.8.8.8: **
```shell
slookup  test.s3-website-us-east-1.amazonaws.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8:53

Non-authoritative answer:
test.s3-website-us-east-1.amazonaws.com	canonical name = s3-website.us-east-1.amazonaws.com

Non-authoritative answer:
test.s3-website-us-east-1.amazonaws.com	canonical name = s3-website.us-east-1.amazonaws.com
Name:	s3-website.us-east-1.amazonaws.com
Address: 52.217.87.195
Name:	s3-website.us-east-1.amazonaws.com
Address: 52.216.27.3
Name:	s3-website.us-east-1.amazonaws.com
Address: 52.216.98.42
Name:	s3-website.us-east-1.amazonaws.com
Address: 52.216.243.67
Name:	s3-website.us-east-1.amazonaws.com
Address: 52.217.140.13
Name:	s3-website.us-east-1.amazonaws.com
Address: 52.216.57.53
Name:	s3-website.us-east-1.amazonaws.com
Address: 52.217.10.139
Name:	s3-website.us-east-1.amazonaws.com
Address: 52.217.137.173
```

I'm using colima's DNS strategy because I need `host.docker.internal` resolution via DNS Lookup, not via `/etc/hosts`

### Version

Colima Version: 0.5.4
Lima Version: 0.15.0
Qemu Version: QEMU emulator version 7.2.0

### Operating System

- [X] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU                 
INFO[0000] arch: x86_64                                 
INFO[0000] runtime: docker                              
INFO[0000] mountType: sshfs                             
INFO[0000] socket: unix:///Users/user/.colima/default/docker.sock 

### Reproduction Steps

1. colima start --edit
2. colima ssh
3. nslookup test.s3-website-us-east-1.amazonaws.com # this doesn't work
4. nslookup test.s3-website-us-east-1.amazonaws.com 8.8.8.8 # This works
5. I've deleted and recreated it multiple times, but the outcome is always the same. for some other S3 DNS entries the DNS is even weirder, like `Parse error`

### Expected behaviour

DNS Lookup should be working for all domains

### Additional context

Colima Config:

```yaml
cpu: 4
disk: 190
memory: 16
arch: x86_64
runtime: docker
kubernetes:
  enabled: false
  version: v1.25.4+k3s1
  disable:
    - traefik
autoActivate: true
network:
  address: false
  dns: []
  dnsHosts: {}
  driver: gvproxy
forwardAgent: false
docker: {}
vmType: qemu
rosetta: false
mountType: sshfs
cpuType: ""
layer: false
provision:
  - mode: system
    script: apk add htop vim
sshConfig: true
mounts:
  - location: ~/
    writable: true
  - location: /tmp/lima
    writable: true
env: {}
```
