### ISSUE TITLE
Allow overriding Lima YAML config

### ISSUE THREAD

**Issue by scalp42** [abiosoft/colima#69]
Hi there,

Thank you again for the project.

Would it be possible to allow passing a YAML to either completely replace the default Lima config or override (think merging with your YAML config)?

The issue is that there's no way to modify `networks` for example (and would not be a good idea imo to port to CLI args).

Let me know your thoughts.

Cheers

**Comment by abiosoft** [comment]
Hi, thanks for the suggestion.

May I know your use-case. Is there any reason you want to modify the network other than for an accessible IP address?

**Comment by scalp42** [comment]
Here's a generic use case:

1. Spin up a VM in Parallels, say Ubuntu and install `redis-cli`.
2. Spin a QEMU VM through Colima, pull and run a Redis container.
3. Allow `redis-cli` inside Parallels VM to talk to `redis` server on Colima side pretty much.

Besides this simple example, in reality, we make heavy use of [Test-Kitchen](https://github.com/test-kitchen/kitchen-vagrant) to drive the Parallels VMs:

```yaml
  - name: client-with-acls-1
    run_list:
      - recipe[my-consul]
    driver:
      pre_create_command: docker-compose up -d consul-server-acl || true
      network:
        - ["private_network", { ip: "192.168.99.103" } ]
    attributes:
        discovery:
          type: manual
          manual:
            - <%= ENV.fetch('DOCKER_IP', '192.168.99.100') %>
```

In this simple example, it'd allow `docker-machine` VM to be accessible to say a Virtualbox VM.

There are plenty of other settings that would be just too much to port to CLI flags but I'm hoping it makes sense

Let me know, thank you again.
