### ISSUE TITLE
Kubernetes does not auto-start when vmType = vz

### ISSUE THREAD

**Issue by codeprefect** [abiosoft/colima#697]
### Description

When you start colima using the following command

```[bash]
colima start -c 4 -d 100 -k --kubernetes-version "v1.26.3+k3s1" -m 4 -t vz --vz-rosetta -v
```

it starts successfully, but running kubectl indicates that the kubernetes environment is not up.
Running `colima start --kubernetes` does not solve it, as it responds with

```[log]
WARN[0000] already running, ignoring
```

This issue does not occur when `vmType = qemu`.

I ran some further tests and I discovered that it actually started, but kept dying for unknown reasons.

Running several `kubectl version --output=yaml` consecutively reveals the following pattern

```
clientVersion:
  buildDate: "2023-04-14T13:14:41Z"
  compiler: gc
  gitCommit: 4c9411232e10168d7b050c49a1b59f6df9d7ea4b
  gitTreeState: clean
  gitVersion: v1.27.1
  goVersion: go1.20.3
  major: "1"
  minor: "27"
  platform: darwin/arm64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-03-27T22:04:57Z"
  compiler: gc
  gitCommit: 01ea3ff27be0b04f945179171cec5a8e11a14f7b
  gitTreeState: clean
  gitVersion: v1.26.3+k3s1
  goVersion: go1.19.7
  major: "1"
  minor: "26"
  platform: linux/arm64
```
and in most cases

```
clientVersion:
  buildDate: "2023-04-14T13:14:41Z"
  compiler: gc
  gitCommit: 4c9411232e10168d7b050c49a1b59f6df9d7ea4b
  gitTreeState: clean
  gitVersion: v1.27.1
  goVersion: go1.20.3
  major: "1"
  minor: "27"
  platform: darwin/arm64
kustomizeVersion: v5.0.1

The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
```

The experience is the same, even when `kubectl version --output=yaml` is ran from within the linux vm.

---------
I went a step further and did the following

```
colima ssh
~colima-vm: tail -f /var/log/k3s.log

--- output ---
Error: failed to run Kubelet: validate service connection: CRI v1 runtime API is not implemented for endpoint "unix:///run/cri-dockerd.sock": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService
time="2023-04-18T16:11:52Z" level=fatal msg="kubelet exited: failed to run Kubelet: validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///run/cri-dockerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"
```

### Version

Colima Version: 0.5.4
Lima Version: 0.15.1
Qemu Version: 7.2.1

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

```[bash]
INFO[0000] colima is running using macOS Virtualization.Framework 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: virtiofs                          
INFO[0000] socket: unix:///Users/mubarakimam/.colima/default/docker.sock 
INFO[0000] kubernetes: enabled
```

### Reproduction Steps

1. Create a new instance using
    
    ```[bash]
    colima start -c 4 -d 100 -k --kubernetes-version "v1.26.3+k3s1" -m 4 -t vz --vz-rosetta -v
    ```

2. Run `kubectl get nodes`

Returns

```[bash]
Get "https://127.0.0.1:6443/api/v1/nodes?limit=500": dial tcp 127.0.0.1:6443: connect: connection refused - error from a previous attempt: EOF
```

### Expected behaviour

`kubectl get nodes` should return list of nodes, and not throw an error.

### Additional context

The `k3s` version I used do not affect this issue, I initially thought that was the issue, hence why I used the latest `k3s`.

An instance created with qemu emulation work as expected, this seems to only affect `vmType=vz` instances
