### ISSUE TITLE
nerdctl compose up: WARN[0000] Ignoring: volume: Bind: [CreateHostPath]

### ISSUE THREAD

**Issue by Nezteb** [abiosoft/colima#715]
### Description

macOS: 13.3.1
Chip: Apple M2 Pro

I have a `docker-compose.yml` file that previously worked fine with Docker Desktop. I fully uninstalled Docker Desktop, installed `colima`, and tried the following:

```
❯ colima delete
are you sure you want to delete colima and all settings? [y/N] y
INFO[0000] deleting colima                              
INFO[0001] deleting ...                                  context=containerd
INFO[0001] done                                         

❯ colima start
INFO[0000] starting colima                              
INFO[0000] runtime: containerd                          
INFO[0000] creating and starting ...                     context=vm
INFO[0014] provisioning ...                              context=containerd
INFO[0014] starting ...                                  context=containerd
INFO[0019] done 

❯ colima nerdctl install
INFO[0000] /usr/local/bin not writable, sudo password required to install nerdctl binary
Password:

❯ nerdctl --version
nerdctl version 1.1.0

❯ pwd
/Users/noah/Git/my-repo/sub-project

❯ ls docker-compose.yml
docker-compose.yml

❯ nerdctl compose up -d
FATA[0000] no configuration file provided: not found
FATA[0000] exit status 1

❯ nerdctl compose -f ./docker-compose.yml up -d
FATA[0000] stat /home/noah.linux/docker-compose.yml: no such file or directory
FATA[0000] exit status 1
```

I assume the `/home/noah.linux` is the mounted home directory in the `colima` VM? If so, I'm not sure why it's `$PWD` is looking in `$HOME`. Perhaps I'm doing something incorrectly, but I couldn't find an existing FAQ or GitHub issue like this.

My config file is below.

### Version

```
❯ colima version
colima version 0.5.4
git commit: feef4176f56a7dea487d43689317a9d7fe9de27e

runtime: containerd
arch: aarch64
client: v1.1.0
server: v1.6.8

❯ limactl --version
limactl version 0.15.1

❯ qemu-img --version
qemu-img version 8.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

### Operating System

- [X] macOS M1 >= 13 (Ventura)

### Output of `colima status`

```
❯ colima status
INFO[0000] colima is running using macOS Virtualization.Framework 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: containerd                          
INFO[0000] mountType: virtiofs
```

### Reproduction Steps

1. Use my `colima` config and a basic `docker-compose.yml` file in a subdirectory of your home directory.
2. `colima start`
3. `nerdctl compose up -d`

### Expected behaviour

The compose stack should start normally.

### Additional context

My `~/.colima/default/colima.yaml` config file:
```yaml
# Number of CPUs to be allocated to the virtual machine.
# Default: 2
cpu: 4

# Size of the disk in GiB to be allocated to the virtual machine.
# NOTE: changing this has no effect after the virtual machine has been created.
# Default: 60
disk: 60

# Size of the memory in GiB to be allocated to the virtual machine.
# Default: 2
memory: 8

# Architecture of the virtual machine (x86_64, aarch64, host).
# Default: host
arch: aarch64

# Container runtime to be used (docker, containerd).
# Default: docker
runtime: containerd

# Kubernetes configuration for the virtual machine.
kubernetes:
  # Enable kubernetes.
  # Default: false
  enabled: false
  
  # Kubernetes version to use.
  # This needs to exactly match a k3s version https://github.com/k3s-io/k3s/releases
  # Default: latest stable release
  version: v1.25.4+k3s1
  
  # Disable k3s features [coredns servicelb traefik local-storage metrics-server].
  # All features are enabled unless disabled.
  #
  # EXAMPLE - disable traefik and metrics-server
  # disable: [traefik, metrics-server]
  #
  # Default: [traefik]
  disable:
    - traefik

# Auto-activate on the Host for client access.
# Setting to true does the following on startup
#  - sets as active Docker context (for Docker runtime).
#  - sets as active Kubernetes context (if Kubernetes is enabled).
# Default: true
autoActivate: true

# Network configurations for the virtual machine.
network:
  # Assign reachable IP address to the virtual machine.
  # NOTE: this is currently macOS only and ignored on Linux.
  # Default: false
  address: false
  
  # Custom DNS resolvers for the virtual machine.
  #
  # EXAMPLE
  # dns: [8.8.8.8, 1.1.1.1]
  #
  # Default: []
  dns: []
  
  # DNS hostnames to resolve to custom targets using the internal resolver.
  # This setting has no effect if a custom DNS resolver list is supplied above.
  # It does not configure the /etc/hosts files of any machine or container.
  # The value can be an IP address or another host.
  #
  # EXAMPLE
  # dnsHosts:
  #   example.com: 1.2.3.4
  dnsHosts: {}
  
  # Network driver to use (slirp, gvproxy), (requires vmType `qemu`)
  #   - slirp is the default user mode networking provided by Qemu
  #   - gvproxy is an alternative to VPNKit based on gVisor https://github.com/containers/gvisor-tap-vsock
  # Default: gvproxy
  driver: gvproxy

# ===================================================================== #
# ADVANCED CONFIGURATION
# ===================================================================== #

# Forward the host's SSH agent to the virtual machine.
# Default: false
forwardAgent: false

# Docker daemon configuration that maps directly to daemon.json.
# https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file.
# NOTE: some settings may affect Colima's ability to start docker. e.g. `hosts`.
#
# EXAMPLE - disable buildkit
# docker:
#   features:
#     buildkit: false
#
# EXAMPLE - add insecure registries
# docker:
#   insecure-registries:
#     - myregistry.com:5000
#     - host.docker.internal:5000
#
# Colima default behaviour: buildkit enabled
# Default: {}
docker: {}

# Virtual Machine type (qemu, vz)
# NOTE: this is macOS 13 only. For Linux and macOS <13.0, qemu is always used.
#
# vz is macOS virtualization framework and requires macOS 13
#
# Default: qemu
vmType: vz

# Utilise rosetta for amd64 emulation (requires m1 mac and vmType `vz`)
# Default: false
rosetta: false

# Volume mount driver for the virtual machine (virtiofs, 9p, sshfs).
#
# virtiofs is limited to macOS and vmType `vz`. It is the fastest of the options.
#
# 9p is the recommended and the most stable option for vmType `qemu`.
#
# sshfs is faster than 9p but the least reliable of the options (when there are lots
# of concurrent reads or writes).
#
# Default: virtiofs (for vz), sshfs (for qemu)
mountType: virtiofs

# The CPU type for the virtual machine (requires vmType `qemu`).
# Options available for host emulation can be checked with: `qemu-system-$(arch) -cpu help`.
# Instructions are also supported by appending to the cpu type e.g. "qemu64,+ssse3".
# Default: host
cpuType: ""

# For a more general purpose virtual machine, Ubuntu container is optionally provided
# as a layer on the virtual machine.
# The underlying virtual machine is still accessible via `colima ssh --layer=false` or running `colima` in
# the Ubuntu session.
#
# Default: false
layer: false

# Custom provision scripts for the virtual machine.
# Provisioning scripts are executed on startup and therefore needs to be idempotent.
#
# EXAMPLE - script exected as root
# provision:
#   - mode: system
#     script: apk add htop vim
#
# EXAMPLE - script exected as user
# provision:
#   - mode: user
#     script: |
#       [ -f ~/.provision ] && exit 0;
#       echo provisioning as $USER...
#       touch ~/.provision
#
# Default: []
provision: []

# Modify ~/.ssh/config automatically to include a SSH config for the virtual machine.
# SSH config will still be generated in ~/.colima/ssh_config regardless.
# Default: true
sshConfig: true

# Configure volume mounts for the virtual machine.
# Colima mounts user's home directory by default to provide a familiar
# user experience.
#
# EXAMPLE
# mounts:
#   - location: ~/secrets
#     writable: false
#   - location: ~/projects
#     writable: true
#
# Colima default behaviour: $HOME and /tmp/colima are mounted as writable.
# Default: []
mounts:
  - location: ~/.docker-conf # I've verified this directory exists and is empty
    writable: true

# Environment variables for the virtual machine.
#
# EXAMPLE
# env:
#   KEY: value
#   ANOTHER_KEY: another value
#
# Default: {}
env: {}
```

**Comment by Nezteb** [comment]
I sort of figured it out, but still get errors, just later in the process.

Part of the problem is:
```yaml
# Configure volume mounts for the virtual machine.
# Colima mounts user's home directory by default to provide a familiar
# user experience.
#
# EXAMPLE
# mounts:
#   - location: ~/secrets
#     writable: false
#   - location: ~/projects
#     writable: true
#
# Colima default behaviour: $HOME and /tmp/colima are mounted as writable.
# Default: []
mounts:
  - location: ~/.docker-conf # I've verified this directory exists and is empty
    writable: true
```

I misunderstood these two lines:
```yaml
# Colima default behaviour: $HOME and /tmp/colima are mounted as writable.
# Default: []
```

I thought it was saying "regardless of what you put here, Colima will mount `$HOME` and `/tmp/colima`, but that's not the case. It's saying "normally without a config file Colima would mount those, but the default when using a config file is no mounts", I think?

All I had to do to fix this was change the config to:
```yaml
mounts:
  - location: ~
    writable: true
```

However, now when running `nerdctl compose up -d` I get:
```
❯ docker compose up -d
INFO[0000] Creating network sub-project_default
INFO[0000] Creating volume sub-project_cassandra_data
INFO[0000] Creating volume sub-project_postgres_data
WARN[0000] Ignoring: volume: Bind: [CreateHostPath]
WARN[0000] Ignoring: volume: Bind: [CreateHostPath]
WARN[0000] Ignoring: volume: Bind: [CreateHostPath]
INFO[0000] Ensuring image redis                         
docker.io/library/redis:latest:                                                   resolved
INFO[0020] Ensuring image postgis/postgis:13-3.1
docker.io/postgis/postgis:13-3.1:                                                 resolved
INFO[0040] Ensuring image rabbitmq
docker.io/library/rabbitmq:latest:                                                resolved
INFO[0058] Ensuring image cassandra:4.0
docker.io/library/cassandra:4.0:                                                  resolved
INFO[0076] Creating container sub-project_cassandra_1
INFO[0076] Creating container sub-project_rabbitmq_1
INFO[0076] Creating container sub-project_postgres_1
INFO[0076] Creating container sub-project_redis_1
FATA[0077] error while creating sub-project_cassandra_1: exit status 1
FATA[0077] exit status 1
```

I assume the issue is:
```
WARN[0000] Ignoring: volume: Bind: [CreateHostPath]
WARN[0000] Ignoring: volume: Bind: [CreateHostPath]
WARN[0000] Ignoring: volume: Bind: [CreateHostPath]
```

Here is most of my `docker-compose.yaml` file:
```yaml
version: '2'
services:
  postgres:
    image: 'postgis/postgis:13-3.1'
    ports:
      - 5432:5432
    volumes:
      - '~/.docker-conf/postgres_data:/var/lib/postgresql/data/'
    environment:
      POSTGRES_PASSWORD: postgres
  rabbitmq:
    image: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
  cassandra:
    image: 'cassandra:4.0'
    environment:
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=512M
    ports:
      - 7001:7000
      - 9042:9042
    volumes:
    - '~/.docker-conf/cassandra_data:/var/lib/cassandra'
  redis:
    image: 'redis'
    ports:
      - 6379:6379
    volumes:
      - '~/.docker-conf/redis_data:/data'

volumes:
  postgres_data:
  cassandra_data:
```

Since `~/.docker-conf` exists under my `$HOME` directory, shouldn't they be fine?

**Comment by Nezteb** [comment]
Okay, I think the issue is this: https://github.com/containerd/nerdctl/issues/1652#issuecomment-1375978871

Which was fixed in https://github.com/containerd/nerdctl/releases/tag/v1.3.1

But `colima` ships with:
```
❯ limactl --version
limactl version 0.15.1

❯ nerdctl --version
nerdctl version 1.1.0
```

It looks like `lima` first bumped to `nerdctl 1.1.0` five months ago: https://github.com/lima-vm/lima/blame/063d4f9b03fdb1155e3ab9238bb8858041216144/pkg/limayaml/defaults.go#L33

`lima` bumped to `nerdctl 1.3.1` a month ago: https://github.com/lima-vm/lima/blame/a235d102720decfc70da8e17d2013257ffa993c1/pkg/limayaml/defaults.go#L35

I tried removing the `nerdctl` alias that `colima nerdctl install` installed, and then:
```
❯ brew info nerdctl
==> nerdctl: stable 1.3.1, HEAD
...

❯ brew install nerdctl
...
nerdctl: Linux is required for this software.
Error: nerdctl: An unsatisfied requirement failed this build.
```

So I think `colima` would need to bump to the latest version of `lima` and thus `nerdctl` to fix this?

**Comment by Nezteb** [comment]
For the time being I've moved from bind mounts to volumes
```yaml
version: '2'
services:
  postgres:
  # ...
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data/
  cassandra:
    # ...
    volumes:
      - type: volume
        source: cassandra_data
        target: /var/lib/cassandra
  redis:
    # ...
    volumes:
      - type: volume
        source: redis_data
        target: /data

volumes:
  postgres_data:
  cassandra_data:
  redis_data:
```

However, it'd be cool to bring bind mount support to Colima by bumping the versions of `lima`/`nerdctl`. 😄
