### ISSUE TITLE
Cluster not able find local images

### ISSUE THREAD

**Issue by mrsauravsahu** [abiosoft/colima#90]
## expected behaviour
Kubernetes Cluster should be able to use images created with `colima nerdctl build`.

## observed behavior
The cluster is not able to find images created with `colima nerdctl build` and tries to pull images.

## system
```
colima version 0.2.2
git commit: b2c7697bee2d73e995f156fe8e9870eb246c07e6

runtime: containerd
client: v0.15.0
server: v1.5.8

kubernetes
Client Version: v1.23.0
Server Version: v1.22.2+k3s2
```

## how to reproduce

- I created an image `ghcr.io/mrsauravsahu/docker-samples/docs-site:0.1.0-alpha.1` with nerdctl.

```bash
$ colima nerdctl build -- -t ghcr.io/mrsauravsahu/docker-samples/docs-site:0.1.0-alpha.1 -f ../common/svelte-kit.dockerfile .
```

I'm able to run the image with 

```bash
$ colima nerdctl run -- -d -p 8080:80 ghcr.io/mrsauravsahu/docker-samples/docs-site:0.1.0-alpha.1
```

I'm trying to connect to run the image inside the colima kubernetes cluster (started with `colima start --with-kubernetes -r containerd`)

This is the deployment.yaml

```yaml
apiVersion: v1
kind: Pod

metadata:
  name: docs-site
spec:
  containers:
    - name: main
      image: ghcr.io/mrsauravsahu/docker-samples/docs-site:0.1.0-alpha.1
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: 250Mi
          cpu: 0.25m
```

The `kubectl apply` fails trying to pull the image (which should be present locally)

```
│ Message:             Failed to pull image "ghcr.io/mrsauravsahu/docker-samples/docs-site:0.1.0-alpha.1": rpc error │
│ : code = Unknown desc = failed to pull and unpack image "ghcr.io/mrsauravsahu/docker-samples/docs-site:0.1.0-alpha │
│ .1": failed to resolve reference "ghcr.io/mrsauravsahu/docker-samples/docs-site:0.1.0-alpha.1": failed to authoriz │
│ e: failed to fetch anonymous token: unexpected status: 401 Unauthorized
```
