### ISSUE TITLE
Can't start Elasticsearch image

### ISSUE THREAD

**Issue by xiongtx** [abiosoft/colima#965]
### Description

Can't start [`elasticsearch:8.11.3`](https://hub.docker.com/layers/library/elasticsearch/8.11.3/images/sha256-0e47a784b266b7f30d8071a25f774b10a38f3bb9bb41e23a2767ba464aafcb21?context=explore) properly. Getting the following error:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1474b78040, pid=7, tid=16
#
# JRE version: OpenJDK Runtime Environment (21.0.1+12) (build 21.0.1+12-29)
# Java VM: OpenJDK 64-Bit Server VM (21.0.1+12-29, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, serial gc, linux-amd64)
# Problematic frame:
# J 187 c1 java.lang.invoke.MethodType.parameterCount()I java.base@21.0.1 (6 bytes) @ 0x00007f1474b78040 [0x00007f1474b78020+0x0000000000000020]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /usr/share/elasticsearch/core.7)
#
# An error report file with more information is saved as:
# /usr/share/elasticsearch/hs_err_pid7.log
[2.934s][warning][os] Loading hsdis library failed
```

Here's the image 

```
$ docker image ls
REPOSITORY                                      TAG       IMAGE ID       CREATED       SIZE
docker.elastic.co/elasticsearch/elasticsearch   8.11.3    792fab0c0bd8   5 weeks ago   1.43GB
```

### Version

colima version 0.6.7
git commit: ba1be00e9aec47f2c1ffdacfb7e428e465f0b58a

runtime: docker
arch: x86_64
client: v23.0.0
server: v24.0.7
limactl version 0.19.1
qemu-img version 8.2.0

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU
INFO[0000] arch: x86_64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/tianxiong.xiong/.colima/default/docker.sock

### Reproduction Steps

1. Use the following `docker-compose.yml`:

```yml
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
```

2. `docker-compose up -d`
3. Wait for the container to fail
4. `docker-compose logs`

### Expected behaviour

Container starts properly.

Running Elasticsearch [directly](https://www.elastic.co/downloads/elasticsearch) works fine.
